---
- name: Install openvpn
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - openvpn
  - openssl

- name: Install configuration file
  copy:
    src: "{{ openvpn_client_config }}"
    dest: /etc/openvpn/client.conf
  notify: restart openvpn